backend = "glx";

glx-no-stencil = true;

glx-copy-from-front = false;

inactive-opacity = 1;
active-opacity = 1;
frame-opacity = 1;
inactive-opacity-override = false;

blur-method = "dual_kawase";
blur-background = true;
blur-strength = 3;
blur-background-frame = true;
blur-background-fixed = false;
#blur-background-exclude = [
#    "window_type = 'dock'",
#    "window_type = 'desktop'"
#];

#corner-radius = 10.0

#rounded-corners-exclude = [
#  "window_type = 'dock'",
#  "window_type = 'desktop'"
#];

shadow = true;
shadow-radius = 12
shadow-radius = 7;
shadow-opacity = .75
shadow-offset-x = -7;
shadow-offset-y = -7;

shadow-exclude = [
  "name = 'Notification'",
  "class_g = 'Conky'",
  "class_g ?= 'Notify-osd'",
  "class_g = 'Cairo-clock'",
  "class_g = 'slop'",
  "class_g = 'Polybar'",
  "_GTK_FRAME_EXTENTS@:c"
];

fading = true;

fade-delta = 4;

fade-in-step = 0.03;

fade-out-step = 0.03;

fade-exclude = [ ];

mark-wmwin-focused = true;

mark-ovredir-focused = true;

use-ewmh-active-win = true;

detect-rounded-corners = true;

detect-client-opacity = true;

vsync = true;

dbe = false;

unredir-if-possible = false;

focus-exclude = [ ];

detect-transient = true;
detect-client-leader = true;

#wintypes:
#{
#  normal = { fade = false; shadow = false; }
#  tooltip = { fade = true; shadow = true; opacity = 0.75; focus = true; full-shadow = false; };
#  dock = { shadow = false; }
#  dnd = { shadow = false; }
#  popup_menu = { opacity = 0.8; }
#  dropdown_menu = { opacity = 0.8; }
#};


xrender-sync-fence = true;

