#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/launch.sh
feh --bg-fill --randomize ~/.config/wallpapers/*
picom --experimental-backends &

bspc monitor -d    漣 ﴑ

bspc config border_width	2
bspc config window_gap          10

bspc config normal_border_color		      "#8c775e"
bspc config active_border_color	              "#8c775e"
bspc config focused_border_color	      "#b59979"
bspc config presel_feedback_color	      "#8c775e"
bspc config urgent_border_color 	      "#8c775e"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

